// The app's words, English + Urdu. Use with <Bi {...W.key} />.
// Rules: docs/DESIGN_SYSTEM.md section 6. Add new words here, never inline a synonym.

export const W = {
  // Navigation
  home: { en: "Home", ur: "ہوم" },
  myBcs: { en: "My BCs", ur: "میری کمیٹیاں" },
  members: { en: "Members", ur: "ممبرز" },
  messages: { en: "Messages", ur: "پیغامات" },
  alerts: { en: "Alerts", ur: "اطلاعات" },
  profile: { en: "Profile", ur: "پروفائل" },
  more: { en: "More", ur: "مزید" },
  explore: { en: "Find BCs", ur: "کمیٹی تلاش کریں" },
  nearMe: { en: "Near me", ur: "میرے قریب" },
  guide: { en: "Help", ur: "مدد" },
  logout: { en: "Log out", ur: "لاگ آؤٹ" },

  // BC
  bc: { en: "BC", ur: "کمیٹی" },
  createBc: { en: "Create BC", ur: "نئی کمیٹی بنائیں" },
  running: { en: "Running now", ur: "جاری کمیٹیاں" },
  comingUp: { en: "Coming up", ur: "آنے والی کمیٹیاں" },
  finished: { en: "Finished", ur: "مکمل" },
  startBc: { en: "Start BC", ur: "کمیٹی شروع کریں" },
  nextMonth: { en: "Next month", ur: "اگلا مہینہ" },
  finishBc: { en: "Finish BC", ur: "کمیٹی مکمل کریں" },
  monthlyAmount: { en: "Monthly amount", ur: "ماہانہ قسط" },
  howManyMembers: { en: "How many members", ur: "کتنے ممبرز" },
  startMonth: { en: "Start month", ur: "شروع کا مہینہ" },
  bcName: { en: "BC name", ur: "کمیٹی کا نام" },
  turnOrder: { en: "Turn order", ur: "باری کی ترتیب" },
  yourTurn: { en: "Your turn", ur: "آپ کی باری" },
  getsThePot: { en: "Gets the pot", ur: "اس ماہ کی باری" },
  pot: { en: "Pot", ur: "کل رقم" },

  // Actions
  pay: { en: "Pay now", ur: "قسط دیں" },
  approve: { en: "Approve", ur: "منظور کریں" },
  reject: { en: "Reject", ur: "رد کریں" },
  markCash: { en: "Paid in cash", ur: "نقد ادا کیا" },
  givePayout: { en: "Give payout", ur: "رقم دیں" },
  remind: { en: "Remind", ur: "یاد دہانی" },
  addMember: { en: "Add member", ur: "ممبر شامل کریں" },
  sendWhatsApp: { en: "Send on WhatsApp", ur: "واٹس ایپ پر بھیجیں" },
  copyLink: { en: "Copy link", ur: "لنک کاپی کریں" },
  askToJoin: { en: "Ask to join", ur: "شامل ہونے کی درخواست" },
  save: { en: "Save", ur: "محفوظ کریں" },
  cancel: { en: "Cancel", ur: "منسوخ" },
  seeAll: { en: "See all", ur: "سب دیکھیں" },
  inviteLink: { en: "Invite link", ur: "دعوت کا لنک" },
  receipt: { en: "Receipt", ur: "رسید" },
  login: { en: "Log in", ur: "لاگ ان" },
  register: { en: "Create account", ur: "اکاؤنٹ بنائیں" },
  emailOrPhone: { en: "Phone or email", ur: "فون یا ای میل" },
  password: { en: "Password", ur: "پاس ورڈ" },
  name: { en: "Full name", ur: "پورا نام" },
  phone: { en: "Mobile number", ur: "موبائل نمبر" },
  email: { en: "Email (optional)", ur: "ای میل (اختیاری)" },
  toDo: { en: "To do", ur: "کرنے کے کام" },
  verifyIdentity: { en: "Verify identity", ur: "شناخت کی تصدیق" },

  // Guide videos
  videoGuide: { en: "Watch the video guide", ur: "ویڈیو گائیڈ دیکھیں" },
  forOrganizers: { en: "For organizers", ur: "منتظم کے لیے" },
  forMembers: { en: "For members", ur: "ممبرز کے لیے" },
};

// Fixed status words and colors (docs/DESIGN_SYSTEM.md section 5).
export const STATUS = {
  verified: { en: "Paid", ur: "ادا ہو گیا", tone: "green" },
  paid: { en: "Paid", ur: "ادا ہو گیا", tone: "green" },
  pending: { en: "Waiting for check", ur: "چیک ہونا باقی", tone: "amber" },
  unpaid: { en: "Not paid", ur: "ادا نہیں ہوا", tone: "gray" },
  rejected: { en: "Sent back", ur: "واپس", tone: "red" },
  receiver: { en: "Gets the pot", ur: "اس ماہ کی باری", tone: "primary" },
  upcoming: { en: "Coming up", ur: "آنے والی", tone: "blue" },
  running: { en: "Running", ur: "جاری", tone: "primary" },
  finished: { en: "Finished", ur: "مکمل", tone: "gray" },
  invited: { en: "Invite sent", ur: "دعوت بھیجی گئی", tone: "amber" },
  request: { en: "Wants to join", ur: "شامل ہونا چاہتے ہیں", tone: "amber" },
  approved: { en: "Active", ur: "فعال", tone: "green" },
  verifiedId: { en: "Verified", ur: "تصدیق شدہ", tone: "green" },
  pendingId: { en: "Checking ID", ur: "شناخت چیک ہو رہی ہے", tone: "amber" },
  given: { en: "Given", ur: "دے دی گئی", tone: "green" },
};
