// Narration steps for the Urdu guide videos. Used by capture.cjs and build.cjs.
// Each step: { id, cap (Urdu caption), en (button label on screen), say (Urdu voiceover),
//   run(p) -> [[locator, closest?], ...] to highlight, after(p) -> optional action once the shot is taken,
//   title: true for a title card (no screenshot), lines: [...] for the closing card }.
// Organizer steps change the demo "ZZTEST Running BC" (approve receipt, cash, payout): re-seed before re-running.

module.exports = ({ BASE, ids, center, sheet, login }) => {
  const ORG = [
    { id: "o00", title: true, cap: "منتظم کے لیے گائیڈ", en: "Organizer guide", say: "السلام علیکم۔ اس ویڈیو میں ہم دیکھیں گے کہ کمیٹی ایپ میں منتظم، یعنی کمیٹی چلانے والا شخص، کیا کرتا ہے۔ ہر بٹن کا مطلب آسان الفاظ میں بتایا جائے گا۔" },
    { id: "o01", cap: "لاگ ان", en: "Log in", say: "ایپ کھولیں۔ اپنا موبائل نمبر یا ای میل لکھیں، اور پھر اپنا پاس ورڈ لکھیں۔",
      run: async (p) => { await p.goto(BASE + "/login", { waitUntil: "networkidle" }); return [[p.getByLabel(/phone/i)], [p.getByLabel(/password/i)]]; } },
    { id: "o02", cap: "لاگ ان کا بٹن", en: "Log in", say: "پھر سبز بٹن، لاگ ان، دبائیں۔ اگر پاس ورڈ بھول جائیں تو نیچے، فارگاٹ پاس ورڈ، دبائیں۔",
      run: async (p) => [[p.locator("button[type=submit]")], [p.getByText(/forgot password/i)]] },
    { id: "o03", cap: "کرنے کے کام", en: "To do", say: "یہ آپ کا ہوم صفحہ ہے۔ سب سے اوپر، کرنے کے کام، کی فہرست ہے۔ یہاں وہ سب کام نظر آتے ہیں جن پر آپ کو توجہ دینی ہے، جیسے رسید چیک کرنا، یا کسی کو کمیٹی میں شامل کرنا۔ کسی کام پر ٹیپ کریں تو سیدھا وہیں پہنچ جائیں گے۔",
      run: async (p) => { await login(p, "+923990000001"); const a = p.getByText(/receipt to check/); await center(a); return [[a, "a,button"], [p.getByText(/wants to join/), "a,button"]]; } },
    { id: "o04", cap: "نئی کمیٹی بنائیں", en: "Create BC", say: "نئی کمیٹی بنانے کے لیے، نئی کمیٹی بنائیں، کا بٹن دبائیں۔ نیچے درمیان میں گول سبز بٹن بھی یہی کام کرتا ہے۔",
      run: async (p) => { await p.evaluate(() => scrollTo(0, 0)); return [[p.getByRole("link", { name: /Create BC/ }).first()]]; } },
    { id: "o05", cap: "نیچے والی پٹی", en: "Home · BCs · Members · More", say: "نیچے والی پٹی سے آپ کہیں بھی جا سکتے ہیں: ہوم، آپ کی کمیٹیاں، ممبرز، اور مزید۔ مزید میں باقی چیزیں ہیں، جیسے دعوت کا لنک اور آپ کی پروفائل۔",
      run: async (p) => [[p.getByRole("link", { name: /^Home/ }).last(), "nav"]] },
    { id: "o06", cap: "کمیٹی کی تفصیل", en: "Create BC", say: "کمیٹی کا نام لکھیں، کتنے ممبرز ہوں گے، اور ہر مہینے کی قسط کتنی ہے۔ پھر شروع کا مہینہ چنیں۔ یاد رکھیں، جتنے ممبرز ہوں گے، اتنے ہی مہینے کمیٹی چلے گی۔",
      run: async (p) => {
        await p.goto(BASE + "/admin/create", { waitUntil: "networkidle" });
        const inputs = p.locator("main input");
        await inputs.nth(0).fill("Family BC 2027"); await inputs.nth(1).fill("5"); await inputs.nth(2).fill("10000");
        return [[inputs.nth(0), ".shadow-card"]];
      } },
    { id: "o07", cap: "کمیٹی بن گئی", en: "Create BC", say: "آخر میں نیچے والا سبز بٹن دبائیں، اور کمیٹی بن جائے گی۔ ہر مہینے جس ممبر کی باری ہو، وہ خود قسط نہیں دیتا، باقی سب دیتے ہیں، اور ساری رقم اسے ملتی ہے۔",
      run: async (p) => { const b = p.locator("main button[type=submit]"); await center(b); return [[b]]; } },
    { id: "o08", cap: "کمیٹی بھر رہی ہے", en: "Members 3 of 5", say: "یہ کمیٹی ابھی بھر رہی ہے۔ یہاں دکھتا ہے کہ پانچ میں سے تین ممبرز آ چکے ہیں، اور کمیٹی کس مہینے سے شروع ہوگی۔",
      run: async (p) => { await p.goto(BASE + "/admin/bc/" + ids["ZZTEST Family BC"], { waitUntil: "networkidle" }); return [[p.getByRole("button", { name: /^Add member/ }).first(), ".shadow-card"]]; } },
    { id: "o09", cap: "ممبر شامل کریں", en: "Add member", say: "ممبر شامل کریں، کا بٹن دبا کر آپ خود کسی کو کمیٹی میں شامل کر سکتے ہیں۔",
      run: async (p) => [[p.getByRole("button", { name: /^Add member/ }).first()]] },
    { id: "o10", cap: "نیا ممبر", en: "Add member", say: "نئے شخص کا پورا نام اور موبائل نمبر لکھیں۔ ای میل ضروری نہیں۔ اگر وہ پہلے سے آپ کا ممبر ہے تو اوپر، میرے ممبرز سے، چن لیں۔ پھر، ممبر شامل کریں، دبائیں۔ اس کے بعد واٹس ایپ پر دعوت بھیجیں، تاکہ ممبر اپنا پاس ورڈ بنا لے۔",
      run: async (p) => { await p.getByRole("button", { name: /^Add member/ }).first().click(); return [[sheet(p)]]; } },
    { id: "o11", cap: "شامل ہونے کی درخواست", en: "Approve", say: "جو لوگ خود شامل ہونے کی درخواست بھیجیں، وہ یہاں نظر آتے ہیں۔ ہرا بٹن، منظور کریں، دبائیں تو وہ کمیٹی میں آ جائیں گے۔ کراس کا نشان دبائیں تو درخواست رد ہو جائے گی۔",
      run: async (p) => { await p.keyboard.press("Escape"); const a = p.getByRole("button", { name: /^Approve/ }); await center(a); return [[a, "li,[class*=border-b],.shadow-card"]]; } },
    { id: "o12", cap: "کمیٹی شیئر کریں", en: "Send on WhatsApp", say: "یہ کمیٹی کا لنک ہے۔ واٹس ایپ پر بھیجیں، دبا کر یہ لنک خاندان کے گروپ میں بھیج دیں۔ لوگ لنک کھول کر اکاؤنٹ بنائیں گے، اور شامل ہونے کی درخواست کریں گے۔",
      run: async (p) => { const a = p.getByText("Send on WhatsApp").first(); await center(a); return [[a, ".shadow-card"]]; } },
    { id: "o13", cap: "کمیٹی شروع کریں", en: "Start BC", say: "جب سب ممبرز پورے ہو جائیں تو، کمیٹی شروع کریں، کا بٹن آ جاتا ہے۔",
      run: async (p) => { await p.goto(BASE + "/admin/bc/" + ids["ZZTEST Office BC"], { waitUntil: "networkidle" }); return [[p.getByRole("button", { name: /Start BC/ })]]; } },
    { id: "o14", cap: "باری کیسے طے ہو", en: "Random draw · Set order myself", say: "اب فیصلہ کریں کہ رقم پہلے کس کو ملے گی۔ قرعہ اندازی، چنیں تو ایپ خود انصاف سے باری بنائے گی۔ ترتیب خود بنائیں، چنیں اگر خاندان نے پہلے سے باری طے کر لی ہے۔ دھیان رہے، کمیٹی شروع ہونے کے بعد باری نہیں بدلی جا سکتی۔",
      run: async (p) => { await p.getByRole("button", { name: /Start BC/ }).click(); return [[sheet(p)]]; } },
    { id: "o15", cap: "اس مہینے کی باری", en: "Gets the pot", say: "یہ چلتی ہوئی کمیٹی ہے۔ اوپر دکھتا ہے کہ کون سا مہینہ چل رہا ہے، اور اس مہینے رقم کس کی باری ہے اور کتنی ہے۔ جس کی باری ہو، وہ اس مہینے قسط نہیں دیتا۔",
      run: async (p) => { await p.keyboard.press("Escape"); await p.goto(BASE + "/admin/bc/" + ids["ZZTEST Running BC"], { waitUntil: "networkidle" }); return [[p.getByText("Gets the pot"), ".shadow-card"]]; } },
    { id: "o16", cap: "اس ماہ کی ادائیگیاں", en: "Paid · Waiting for check · Not paid", say: "نیچے اس مہینے کی ادائیگیاں ہیں۔ ہر نام کے ساتھ رنگ بتاتا ہے: ہرا مطلب ادا ہو گیا۔ پیلا مطلب رسید آئی ہے اور چیک کرنی ہے۔ سرمئی مطلب ابھی ادا نہیں ہوا۔",
      run: async (p) => { const a = p.getByText("Paid (cash)"); await center(a); return [[p.getByText("Waiting for check").first()], [a], [p.getByText("Not paid").first()]]; } },
    { id: "o17", cap: "رسید چیک کریں", en: "Check receipt", say: "جب ممبر رسید بھیجے تو، رسید چیک کریں، کا بٹن آتا ہے۔ اسے دبائیں۔",
      run: async (p) => { const b = p.getByRole("button", { name: /Check receipt/ }); await center(b); return [[b]]; } },
    { id: "o18", cap: "منظور کریں یا ناٹ کریکٹ", en: "Approve · Not correct", say: "رسید کی تصویر، رقم اور حوالہ نمبر دیکھیں۔ اگر سب ٹھیک ہے تو ہرا بٹن، اپروو، یعنی منظور کریں، دبائیں۔ اگر کچھ غلط ہے تو، ناٹ کریکٹ، دبا کر وجہ لکھیں۔ ممبر دوبارہ رسید بھیج دے گا۔",
      run: async (p) => { await p.getByRole("button", { name: /Check receipt/ }).click(); return [[sheet(p)]]; },
      after: async (p) => { await sheet(p).getByRole("button", { name: /^Approve/ }).click(); await p.waitForTimeout(2500); } },
    { id: "o19", cap: "نقد ادا کیا · یاد دہانی", en: "Paid in cash · Remind", say: "اگر کسی نے نقد رقم ہاتھ میں دی ہے تو، نقد ادا کیا، دبائیں۔ اگر کسی نے ابھی تک قسط نہیں دی تو، یاد دہانی، دبائیں۔ اسے یاد دہانی کا پیغام چلا جائے گا۔",
      run: async (p) => { const b = p.getByRole("button", { name: /Paid in cash/ }); await center(b); return [[b], [p.getByRole("button", { name: /Remind/ })]]; },
      after: async (p) => { await p.getByRole("button", { name: /Paid in cash/ }).click(); await p.getByRole("button", { name: /Yes, paid/ }).click(); await p.waitForTimeout(2500); } },
    { id: "o20", cap: "رقم دیں", en: "Give payout", say: "جب سب کی قسط آ جائے تو یہ بٹن آتا ہے، رقم دیں۔ جب آپ باری والے ممبر کو پوری رقم دے دیں، تب یہ دبائیں۔",
      run: async (p) => { const b = p.getByRole("button", { name: /Give payout/ }); await center(b); return [[b]]; } },
    { id: "o21", cap: "رقم دینے کا ریکارڈ", en: "Cash · Bank / mobile · I have given", say: "اب بتائیں کہ رقم کیسے دی۔ نقد دی ہے تو، کیش، چنیں۔ بینک، جاز کیش یا ایزی پیسہ سے بھیجی ہے تو، بینک موبائل، چنیں۔ رقم چیک کریں، اور پھر سبز بٹن، آئی ہیو گِوَن، یعنی میں نے رقم دے دی، دبائیں۔",
      run: async (p) => { await p.getByRole("button", { name: /Give payout/ }).click(); return [[sheet(p)]]; },
      after: async (p) => { const s = sheet(p); await s.locator("button").last().click(); await p.waitForTimeout(800); const y = p.getByRole("button", { name: /^Yes/ }); if (await y.count()) await y.first().click(); await p.waitForTimeout(2500); } },
    { id: "o22", cap: "اگلا مہینہ", en: "Next month", say: "رقم دینے کے بعد، اگلا مہینہ، دبائیں۔ کمیٹی اگلے مہینے پر چلی جائے گی، اور سب کو اطلاع مل جائے گی۔ آخری مہینے میں یہی بٹن، کمیٹی مکمل کریں، بن جاتا ہے۔",
      run: async (p) => { const b = p.getByRole("button", { name: /Next month|Finish BC/ }); await center(b); return [[b]]; } },
    { id: "o23", cap: "مزید", en: "More", say: "مزید، کے بٹن میں یہ چیزیں ہیں: تفصیل بدلیں، باری کی ترتیب دیکھیں، پچھلے مہینوں کا حساب دیکھیں، اور ضرورت پڑے تو کمیٹی جلدی ختم کریں۔ لال بٹن سوچ سمجھ کر دبائیں۔",
      run: async (p) => { await p.evaluate(() => scrollTo(0, 0)); await p.getByRole("button", { name: /^More/ }).first().click(); return [[sheet(p)]]; } },
    { id: "o24", cap: "مکمل کمیٹی", en: "Finished", say: "جب کمیٹی مکمل ہو جائے تو یہاں سب کا پورا حساب نظر آتا ہے: کس مہینے کس کو کتنی رقم ملی۔",
      run: async (p) => { await p.keyboard.press("Escape"); await p.goto(BASE + "/admin/bc/" + ids["ZZTEST Finished BC"], { waitUntil: "networkidle" }); return [[p.getByText("This BC is complete"), ".shadow-card"], [p.getByText(/Rs\s*6,000/).last(), ".shadow-card"]]; } },
    { id: "o25", cap: "ممبرز", en: "Members", say: "ممبرز، میں آپ کے سب ممبرز ہیں۔ نام یا نمبر سے تلاش کریں۔ ہرا نشان، تصدیق شدہ، کا مطلب ہے کہ ان کا شناختی کارڈ چیک ہو چکا ہے۔",
      run: async (p) => { await p.goto(BASE + "/admin/members", { waitUntil: "networkidle" }); return [[p.getByRole("searchbox").or(p.getByPlaceholder(/search/i)).first()], [p.getByText(/Verified/).first(), ".shadow-card"]]; } },
    { id: "o26", cap: "ممبر کی تفصیل", en: "Call · WhatsApp · Add to a BC · New password link", say: "کسی ممبر پر ٹیپ کریں تو اسے کال یا واٹس ایپ کر سکتے ہیں۔ ایڈ ٹو اے بی سی، سے اسے کسی کمیٹی میں ڈالیں۔ اگر ممبر پاس ورڈ بھول جائے تو، نیو پاس ورڈ لنک، دبا کر نیا لنک واٹس ایپ پر بھیجیں۔",
      run: async (p) => { await p.getByText(/Fatima/).first().click(); return [[sheet(p)]]; } },
    { id: "o27", cap: "دعوت کا لنک", en: "Invite link", say: "دعوت کا لنک، آپ کا اپنا لنک ہے۔ اسے واٹس ایپ پر بھیجیں۔ جو بھی اس لنک سے اکاؤنٹ بنائے گا، وہ آپ کے ممبرز کی فہرست میں آ جائے گا۔",
      run: async (p) => { await p.keyboard.press("Escape"); await p.goto(BASE + "/admin/invite", { waitUntil: "networkidle" }); await p.waitForTimeout(1500); return [[p.getByText(/WhatsApp/).first(), ".shadow-card"]]; } },
    { id: "o28", cap: "اطلاعات", en: "Alerts", say: "اوپر گھنٹی کے نشان پر نئی اطلاعات آتی ہیں، جیسے کسی نے رسید بھیجی، یا کوئی شامل ہونا چاہتا ہے۔",
      run: async (p) => { await p.goto(BASE + "/admin", { waitUntil: "networkidle" }); return [[p.locator('header a[href="/admin/notifications"]').first()]]; } },
    { id: "o29", title: true, cap: "ہر مہینے کا کام", en: "Every month", say: "ہر مہینے کا کام یاد رکھیں۔ رسیدیں چیک کریں۔ نقد دینے والوں کا، نقد ادا کیا، دبائیں۔ باری والے کو رقم دیں۔ اور، اگلا مہینہ، دبائیں۔ کسی مدد کے لیے ایپ میں، مدد، کا صفحہ دیکھیں۔ شکریہ۔",
      lines: ["۱۔ رسیدیں چیک کریں", "۲۔ نقد والوں کا «نقد ادا کیا» دبائیں", "۳۔ باری والے کو «رقم دیں»", "۴۔ «اگلا مہینہ» دبائیں"] },
  ];

  const MEM = [
    { id: "m00", title: true, cap: "ممبر کے لیے گائیڈ", en: "Member guide", say: "السلام علیکم۔ اس ویڈیو میں ہم دیکھیں گے کہ کمیٹی کے ممبر ایپ میں کیا کرتے ہیں: قسط کیسے دیں، اپنی باری کیسے دیکھیں، اور نئی کمیٹی میں کیسے شامل ہوں۔" },
    { id: "m01", cap: "لاگ ان", en: "Log in", say: "اگر منتظم نے آپ کو کمیٹی میں شامل کیا ہے تو واٹس ایپ پر ایک لنک آئے گا۔ اس لنک سے اپنا پاس ورڈ بنائیں۔ اس کے بعد ہمیشہ اپنا موبائل نمبر اور پاس ورڈ لکھ کر، لاگ ان، دبائیں۔",
      run: async (p) => { await p.goto(BASE + "/login", { waitUntil: "networkidle" }); return [[p.getByLabel(/phone/i)], [p.locator("button[type=submit]")]]; } },
    { id: "m02", cap: "نیا اکاؤنٹ", en: "Create an account", say: "اگر آپ خود نیا اکاؤنٹ بنانا چاہتے ہیں تو نیچے، کریئیٹ این اکاؤنٹ، دبائیں۔ موبائل نمبر اور پاس ورڈ کافی ہے، ای میل ضروری نہیں۔",
      run: async (p) => { const a = p.getByText(/Create an account/); await center(a); return [[a]]; } },
    { id: "m03", cap: "اس مہینے کی قسط", en: "Pay now", say: "یہ آپ کا ہوم صفحہ ہے۔ سب سے اوپر بتایا جاتا ہے کہ اس مہینے آپ کو کتنی قسط دینی ہے۔ پے ناؤ، دبا کر قسط دیں۔",
      run: async (p) => { await login(p, "+923990000102"); return [[p.getByText(/^Pay Rs/).first(), "a,button,[class*=rounded-xl]"]]; } },
    { id: "m04", cap: "میری کمیٹیاں", en: "My BCs", say: "میری کمیٹیاں، میں آپ کی سب کمیٹیاں ہیں۔ یہاں دکھتا ہے کہ کون سا مہینہ چل رہا ہے، اور آپ کی باری کب ہے۔",
      run: async (p) => { const a = p.getByText(/Your turn/).first(); await center(a, ".shadow-card"); return [[a, ".shadow-card"]]; } },
    { id: "m05", cap: "شامل ہونے کی درخواست", en: "Ask to join", say: "نیچے آپ کے منتظم کی نئی کمیٹیاں نظر آتی ہیں۔ شامل ہونے کی درخواست، دبائیں۔ منتظم منظور کرے گا تو آپ شامل ہو جائیں گے۔ اگر کمیٹی بھر چکی ہو تو یہ بٹن ہلکا ہو جاتا ہے۔",
      run: async (p) => { const a = p.getByRole("button", { name: /Ask to join/ }).first(); await center(a, ".shadow-card"); return [[a, ".shadow-card"]]; } },
    { id: "m06", cap: "قسط دیں · آپ کی باری", en: "Pay now · Your turn", say: "کمیٹی کھولیں تو سب سے اوپر، پے ناؤ، کا بٹن اور رقم ہے۔ نیچے لکھا ہے کہ آپ کی باری کس مہینے ہے، اور آپ کو کتنی رقم ملے گی۔",
      run: async (p) => { await p.goto(BASE + "/userDash/bc/" + ids["ZZTEST Running BC"], { waitUntil: "networkidle" }); return [[p.getByRole("button", { name: /Pay now/ }), ".shadow-card"]]; } },
    { id: "m07", cap: "میری ادائیگیاں", en: "My payments", say: "میری ادائیگیاں، میں ہر مہینے کا حال ہے۔ ہرا، ادا ہو گیا، مطلب منتظم نے آپ کی قسط منظور کر لی۔ سرمئی، ادا نہیں ہوا، مطلب ابھی قسط باقی ہے۔ پیلا، چیک ہونا باقی، مطلب رسید بھیج دی ہے اور منتظم چیک کرے گا۔ لال، واپس، مطلب رسید میں کچھ غلط تھا، دوبارہ بھیجیں۔",
      run: async (p) => { const a = p.getByText("Not paid").first(); await center(a, ".shadow-card"); return [[a, ".shadow-card"]]; } },
    { id: "m08", cap: "باری کی ترتیب", en: "Turn order", say: "باری کی ترتیب، میں دکھتا ہے کہ کس مہینے کس کو رقم ملے گی۔ جہاں، یو، یعنی آپ لکھا ہے، وہ آپ کی باری ہے۔",
      run: async (p) => { const a = p.getByText("This month", { exact: true }); await center(a, ".shadow-card"); return [[a, ".shadow-card"]]; } },
    { id: "m09", cap: "منتظم سے رابطہ", en: "Message · WhatsApp", say: "منتظم سے بات کرنی ہو تو، میسج، یا، واٹس ایپ، کا بٹن دبائیں۔",
      run: async (p) => { const a = p.getByRole("button", { name: /^Message/ }).or(p.getByRole("link", { name: /^Message/ })).first(); await center(a, ".shadow-card"); return [[a, ".shadow-card"]]; } },
    { id: "m10", cap: "رسید بھیجیں", en: "Take photo · From gallery · Send receipt", say: "قسط دینے کا طریقہ: پہلے بینک، جاز کیش یا ایزی پیسہ سے رقم بھیجیں۔ پھر یہاں رسید کی تصویر لگائیں۔ ٹیک فوٹو، سے کیمرہ کھلے گا، یا، فرام گیلری، سے پرانی تصویر چنیں۔ آخر میں، سینڈ رسیٹ، دبائیں۔ اگر قسط نقد دی ہے تو منتظم خود اسے ادا شدہ لگا دے گا۔",
      run: async (p) => { await p.evaluate(() => scrollTo(0, 0)); await p.getByRole("button", { name: /Pay now/ }).click(); await p.waitForTimeout(600); return [[sheet(p).getByText("Take photo"), "button,label"], [sheet(p).getByText("From gallery"), "button,label"], [sheet(p).getByRole("button", { name: /Send receipt/ })]]; } },
    { id: "m11", cap: "کمیٹی تلاش کریں", en: "Find BCs", say: "فائنڈ، یعنی تلاش، میں آپ نئی کمیٹیاں ڈھونڈ سکتے ہیں، اور ان میں شامل ہونے کی درخواست بھیج سکتے ہیں۔",
      run: async (p) => { await p.keyboard.press("Escape"); await p.goto(BASE + "/userDash/explore", { waitUntil: "networkidle" }); await p.waitForTimeout(1500); return [[p.getByRole("link", { name: /^Find/ }).last()]]; } },
    { id: "m12", cap: "رقم کہاں بھیجیں", en: "Where to send your payout", say: "پروفائل، میں اپنا اکاؤنٹ ضرور لکھیں۔ جب آپ کی باری آئے گی تو منتظم اسی اکاؤنٹ میں رقم بھیجے گا۔ یہیں سے آپ اپنا پاس ورڈ بھی بدل سکتے ہیں۔",
      run: async (p) => { await p.goto(BASE + "/userDash/profile", { waitUntil: "networkidle" }); const a = p.getByText("Where to send your payout"); await center(a, ".shadow-card"); return [[p.getByLabel("Account name"), ".shadow-card"]]; } },
    { id: "m13", cap: "اطلاعات", en: "Alerts", say: "اوپر گھنٹی کے نشان پر اطلاعات آتی ہیں، جیسے قسط کی یاد دہانی، یا کمیٹی شروع ہونے کی خبر۔",
      run: async (p) => { await p.goto(BASE + "/userDash", { waitUntil: "networkidle" }); return [[p.locator('header a[href="/userDash/notifications"]').first()]]; } },
    { id: "m14", title: true, cap: "یاد رکھیں", en: "Remember", say: "یاد رکھیں۔ ہر مہینے وقت پر قسط دیں، اور رسید بھیجیں۔ اپنی پروفائل میں اپنا اکاؤنٹ لکھیں۔ پاس ورڈ بھول جائیں تو اپنے منتظم سے نیا لنک مانگیں، وہ واٹس ایپ پر بھیج دے گا۔ شکریہ۔",
      lines: ["۱۔ ہر مہینے وقت پر قسط دیں", "۲۔ رسید کی تصویر بھیجیں", "۳۔ پروفائل میں اپنا اکاؤنٹ لکھیں", "۴۔ پاس ورڈ بھولیں تو منتظم سے لنک مانگیں"] },
  ];

  return { ORG, MEM };
};
